# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-30 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0004_auto_20171122_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
