# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-30 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0005_auto_20171130_1123'),
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='wished_by',
            field=models.ManyToManyField(related_name='wishing_for', to='login_reg.User'),
        ),
    ]
